"""Canonical, machine-readable description of every Drakkar config field.

Generated by walking :class:`~drakkar.config.DrakkarConfig`'s pydantic model
tree (never hand-maintained), so it can never drift from the fields the
config loader actually accepts. The output is committed as
``drakkar/uiserver/config-metadata.json`` — the same "generate once, vendor
the artifact" pattern already used for the OpenAPI spec
(``drakkar/uiserver/openapi.yaml``) — so the Go backend and the debug-UI
frontend can consume one canonical source instead of each re-deriving field
lists from source.

Run ``python -m drakkar.configmeta`` to regenerate the artifact after a
config model change; ``tests/test_configmeta.py`` fails loudly (with that
command in the message) if the committed file drifts from the live model
tree.
"""

from __future__ import annotations

import enum
import re
import types
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin

from pydantic import BaseModel, SecretStr
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from drakkar.config import (
    CacheConfig,
    DLQConfig,
    DrakkarConfig,
    ExecutorConfig,
    KafkaConfig,
    LoggingConfig,
    MetricsConfig,
    OffloadConfig,
    RuntimeHealthConfig,
    SinksConfig,
    UIConfig,
    WebAppConfig,
)

# The artifact this module regenerates. Mirrors the vendored-OpenAPI-spec
# location (``drakkar/uiserver/openapi.yaml``) so both generated contracts
# live next to the server code that serves them.
ARTIFACT_PATH = Path(__file__).parent / 'uiserver' / 'config-metadata.json'


class ConfigFieldMeta(BaseModel):
    """Everything the Configs debug-UI tab needs to render one config field."""

    path: str
    """Dot-separated YAML path. A dynamic map key (sink/webapp-client instance
    name) renders as a literal ``*`` segment — e.g. ``sinks.kafka.*.topic`` —
    since the real key is operator-chosen and not part of the schema."""

    env: str | None
    """``DK_``-prefixed environment-variable override, ``__``-joined per
    nesting level. ``None`` for any path containing a ``*`` segment: see the
    module-level ``_ENV_NONE_FOR_DYNAMIC_PATHS`` note for why that is the
    truthful answer rather than a guess at a per-instance name."""

    description: str
    """First sentence of the field's ``Field(description=...)``, or ``''``
    when the field carries no description."""

    full_description: str
    """The complete ``Field(description=...)`` text, or ``''``."""

    type: str
    """Simple JSON-ish type name: string/integer/number/boolean/array/object."""

    default: Any
    """JSON-safe default value. ``None`` for required fields (no default
    exists) — indistinguishable from an actual ``None`` default, which is
    acceptable for a display hint; the schema-level ``required``-ness is not
    tracked separately here because no consumer needs it yet (YAGNI)."""

    secret: bool
    """True when the field was marked ``json_schema_extra={'drakkar_secret': True}``
    in ``drakkar/config.py`` / ``drakkar/kafka_security.py`` — the field can
    carry a credential and a UI should mask or omit its value."""

    group: str
    """Top-level section key (``root``, ``kafka``, ``executor``, ``sinks``, …)."""


class ConfigGroupMeta(BaseModel):
    """One top-level config section, anchored into the docs page."""

    key: str
    title: str
    doc_anchor: str
    """Anchor on https://wlame.github.io/drakkar/config-reference/, e.g.
    ``kafka-source-kafka`` for ``#kafka-source-kafka``."""
    entries: list[ConfigFieldMeta]


class ConfigMetadata(BaseModel):
    """The whole tree: every group, in declaration order."""

    groups: list[ConfigGroupMeta]


# --- group -> docs anchor -----------------------------------------------
#
# (group key, human title, docs anchor, model class or None for the root
# scalars). The anchor is the mkdocs-generated id of the matching `##`
# heading in docs/config-reference.md, verified against the live site
# (https://wlame.github.io/drakkar/config-reference/) rather than assumed:
# mkdocs' slugifier lowercases the heading, drops markdown code-span
# backticks, and collapses every run of non-alphanumeric characters
# (spaces, `/`, `(`, `)`, `:`, …) into a single hyphen. `_mkdocs_anchor`
# below implements exactly that and is exercised by the anchor-parity test
# against the doc's actual `##` headings, so this table cannot silently
# drift from the page it points into.
_GROUP_DEFS: list[tuple[str, str, str, type[BaseModel] | None]] = [
    ('root', 'Worker identity', 'worker-identity', None),
    ('kafka', 'Kafka source (kafka:)', 'kafka-source-kafka', KafkaConfig),
    ('executor', 'Executor pool (executor:)', 'executor-pool-executor', ExecutorConfig),
    ('sinks', 'Sinks (sinks:)', 'sinks-sinks', SinksConfig),
    ('dlq', 'Dead letter queue (dlq:)', 'dead-letter-queue-dlq', DLQConfig),
    ('metrics', 'Metrics (metrics:)', 'metrics-metrics', MetricsConfig),
    ('runtime_health', 'Runtime health (runtime_health:)', 'runtime-health-runtime-health', RuntimeHealthConfig),
    ('offload', 'Offload pool (offload:)', 'offload-pool-offload', OffloadConfig),
    ('logging', 'Logging (logging:)', 'logging-logging', LoggingConfig),
    ('ui', 'UI / Flight Recorder (ui:)', 'ui-flight-recorder-ui', UIConfig),
    ('cache', 'Cache (cache:)', 'cache-cache', CacheConfig),
    ('webapp', 'Webapp (webapp:)', 'webapp-webapp', WebAppConfig),
]


def _mkdocs_anchor(heading_text: str) -> str:
    """Reproduce mkdocs' (Python-Markdown TOC extension) heading-id slug.

    Strip markdown code-span backticks (their content stays, e.g.
    ``` `kafka:` ``` -> ``kafka:``), lowercase, then collapse every run of
    non-alphanumeric characters to one hyphen and trim the ends. Verified
    against the live rendered page rather than guessed — see the docstring
    on ``_GROUP_DEFS``.
    """
    text = heading_text.replace('`', '')
    slug = re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')
    return slug


# --- env-var override decision for dynamic-instance (`*`) paths ---------
#
# ``load_config`` (drakkar/config.py) builds env overrides by lower-casing
# each `__`-delimited segment and deep-merging the result onto the parsed
# YAML dict, matched by literal dict key — see `_parse_env_overrides` and
# `_deep_merge`. There is no key-normalisation step for map keys. That
# matters for sink/webapp-client instance names containing a hyphen: YAML
# `sinks.postgres.main-db` and env segment `MAIN_DB` lower-case to
# different dict keys (`main-db` vs `main_db`), so
# `DK_SINKS__POSTGRES__MAIN_DB__DSN` does NOT override the `main-db`
# instance — it silently creates a second, mostly-empty `main_db` instance
# alongside it (confirmed empirically: see the config-metadata report for
# the reproduction). docs/config-reference.md's env cheatsheet claims
# "Drakkar lowercases the env path on parse, then matches it against the
# YAML keys" for hyphenated map keys, which is not actually implemented on
# the Python backend.
#
# Given that, ConfigFieldMeta.env is `None` for every path containing a
# `*` segment: there is no single fixed env-var name for a dynamic-instance
# field (the real var embeds an operator-chosen instance name), and
# claiming a templated one (e.g. `DK_SINKS__POSTGRES__*__DSN`) would imply
# a guarantee the loader does not honor for the common case of a hyphenated
# instance name. `None` is the truthful answer, not a shortcut.
_ENV_NONE_FOR_DYNAMIC_PATHS = True


def _is_basemodel(annotation: Any) -> bool:
    return isinstance(annotation, type) and issubclass(annotation, BaseModel)


def _dict_of_model_value_type(annotation: Any) -> type[BaseModel] | None:
    """Return the value-model class if ``annotation`` is ``dict[str, SomeModel]``."""
    if get_origin(annotation) is dict:
        args = get_args(annotation)
        if len(args) == 2 and _is_basemodel(args[1]):
            return args[1]
    return None


# Candidate sentence-end punctuation: a run of `.`/`!`/`?` immediately
# followed by whitespace or end of string. Not every candidate is a real
# boundary — see `_first_sentence`.
_CANDIDATE_SENTENCE_END_RE = re.compile(r'[.!?]+(?=\s|$)')

# Abbreviations whose trailing period is not a sentence boundary. Checked
# against the text immediately before a candidate boundary, case-
# insensitively. Python's `re` module cannot express these as one
# fixed-width lookbehind (they're different lengths), so `_first_sentence`
# checks them in plain Python instead of pushing them into the regex.
_ABBREVIATIONS = ('e.g', 'i.e', 'etc', 'vs')

# Characters that plausibly start a new sentence: an uppercase letter, a
# digit (e.g. a version number), an opening quote/backtick, or nothing
# (end of string). A lowercase letter or symbol immediately after the
# whitespace means the punctuation was inside the sentence (a decimal, an
# abbreviation not in the list above, …), not a boundary.
_SENTENCE_START_CHARS = '"\'`'


def _first_sentence(text: str) -> str:
    """First sentence of ``text``, guarding against abbreviations.

    A plain "split on `. `" would cut ``'... this backend is built against
    (e.g. "v1.2.0"); the contract is API-major compatible.'`` at ``'e.g.'``,
    losing the rest of the (single) real sentence. Every candidate boundary
    is checked two ways before it's accepted: the text right before it must
    not end in a known abbreviation stem (``e.g``, ``i.e``, ``etc``, ``vs``),
    and the text right after it must look like the start of a new sentence
    (uppercase letter, digit, opening quote/backtick, or end of string).
    Not a full NLP sentence splitter — hand-written Field descriptions don't
    need one — but see module tests for the concrete cases it's proven
    against, including that exact "(e.g. ...)" description.
    """
    if not text:
        return ''
    stripped = text.strip()
    for match in _CANDIDATE_SENTENCE_END_RE.finditer(stripped):
        before = stripped[: match.start()].rstrip().lower()
        if any(before.endswith(abbr) for abbr in _ABBREVIATIONS):
            continue
        after = stripped[match.end() :].lstrip()
        if after and not (after[0].isupper() or after[0].isdigit() or after[0] in _SENTENCE_START_CHARS):
            continue
        return stripped[: match.end()].strip()
    return stripped


def _to_jsonable(value: Any) -> Any:
    """Turn a Python default value (as produced by pydantic) into JSON-safe data."""
    if isinstance(value, SecretStr):
        return value.get_secret_value()
    if isinstance(value, BaseModel):
        return value.model_dump(mode='json')
    if isinstance(value, enum.Enum):
        return value.value
    if isinstance(value, (list, tuple)):
        return [_to_jsonable(v) for v in value]
    if isinstance(value, dict):
        return {k: _to_jsonable(v) for k, v in value.items()}
    return value


def _json_type(annotation: Any) -> str:
    """Collapse a Python/pydantic type annotation to a simple JSON-ish type name."""
    origin = get_origin(annotation)

    if origin is Union or origin is types.UnionType:
        branches = [a for a in get_args(annotation) if a is not type(None)]
        if len(branches) == 1:
            return _json_type(branches[0])
        # A genuine multi-type union (e.g. MongoStatementConfig.update:
        # dict[...] | list[...] | None) has no single JSON type. Prefer
        # 'object' then 'array' since those are this codebase's only
        # multi-branch cases; otherwise fall back to the first branch.
        kinds = [_json_type(b) for b in branches]
        if 'object' in kinds:
            return 'object'
        if 'array' in kinds:
            return 'array'
        return kinds[0] if kinds else 'string'

    if origin is Literal:
        args = get_args(annotation)
        return _json_type(type(args[0])) if args else 'string'

    if origin in (list, set, frozenset, tuple):
        return 'array'

    if origin is dict:
        return 'object'

    if isinstance(annotation, type):
        if issubclass(annotation, bool):  # must precede int: bool is an int subclass
            return 'boolean'
        if issubclass(annotation, enum.Enum):
            return 'string'  # every enum in this config tree is string-valued
        if issubclass(annotation, int):
            return 'integer'
        if issubclass(annotation, float):
            return 'number'
        if issubclass(annotation, (str, SecretStr)):
            return 'string'
        if issubclass(annotation, BaseModel):
            return 'object'

    return 'string'


def _is_secret(field_info: FieldInfo) -> bool:
    extra = field_info.json_schema_extra
    return isinstance(extra, dict) and bool(extra.get('drakkar_secret'))


def _build_leaf(field_info: FieldInfo, path_segments: list[str], group: str) -> ConfigFieldMeta:
    path = '.'.join(path_segments)
    is_dynamic = '*' in path_segments
    env = None if is_dynamic else 'DK_' + '__'.join(seg.upper() for seg in path_segments)

    description = field_info.description or ''

    default_raw = field_info.get_default(call_default_factory=True)
    default = None if default_raw is PydanticUndefined else _to_jsonable(default_raw)

    return ConfigFieldMeta(
        path=path,
        env=env,
        description=_first_sentence(description),
        full_description=description,
        type=_json_type(field_info.annotation),
        default=default,
        secret=_is_secret(field_info),
        group=group,
    )


def _walk(model_cls: type[BaseModel], path_segments: list[str], group: str, out: list[ConfigFieldMeta]) -> None:
    """Recursively append every leaf field of ``model_cls`` to ``out``.

    Nested single-model fields recurse in place (path extended by the field
    name). A ``dict[str, SomeModel]`` field — a sink/statement/client
    instance map — recurses through ``SomeModel`` with a literal ``*``
    path segment standing in for the operator-chosen instance name.
    ``list[SomeModel]`` fields (just ``webapp.clients``) are deliberately
    NOT decomposed the same way: a list has no stable per-element path, so
    it is reported as one ``array``-typed leaf instead.

    CAVEAT for the eventual Configs-tab endpoint: because ``webapp.clients``
    is one un-decomposed leaf, ``ConfigFieldMeta.secret`` is never set for
    it, even though its elements are ``WebClientConfig`` and
    ``WebClientConfig.token`` IS marked secret at the model level (see
    ``drakkar/config.py``). A value-rendering endpoint must special-case
    masking inside the ``webapp.clients`` array (mask each element's
    ``token``) rather than trusting the top-level ``secret`` flag to cover
    it — this module's tree has no per-list-element path to hang a flag on.
    """
    for name, info in model_cls.model_fields.items():
        annotation = info.annotation
        full_path = [*path_segments, name]

        if _is_basemodel(annotation):
            _walk(annotation, full_path, group, out)
            continue

        value_model = _dict_of_model_value_type(annotation)
        if value_model is not None:
            _walk(value_model, [*full_path, '*'], group, out)
            continue

        out.append(_build_leaf(info, full_path, group))


def build_config_metadata() -> ConfigMetadata:
    """Walk :class:`DrakkarConfig` and return the full canonical metadata tree."""
    entries_by_group: dict[str, list[ConfigFieldMeta]] = {key: [] for key, *_rest in _GROUP_DEFS}

    for field_name, field_info in DrakkarConfig.model_fields.items():
        annotation = field_info.annotation
        if _is_basemodel(annotation):
            # Every nested-model field on DrakkarConfig shares its name with
            # its group key (kafka/executor/sinks/dlq/metrics/logging/ui/
            # cache/webapp) — see _GROUP_DEFS.
            _walk(annotation, [field_name], field_name, entries_by_group[field_name])
        else:
            entries_by_group['root'].append(_build_leaf(field_info, [field_name], 'root'))

    groups = [
        ConfigGroupMeta(key=key, title=title, doc_anchor=anchor, entries=entries_by_group[key])
        for key, title, anchor, _model in _GROUP_DEFS
    ]
    return ConfigMetadata(groups=groups)


def _write_artifact() -> None:
    payload = build_config_metadata().model_dump_json(indent=2)
    ARTIFACT_PATH.write_text(payload + '\n')


if __name__ == '__main__':  # pragma: no cover -- trivial CLI wrapper, exercised via subprocess in tests
    _write_artifact()
    print(f'Wrote {ARTIFACT_PATH}')
