"""Regenerate the shared recorder event-type vocabulary fixture.

The vocabulary is a cross-backend contract: both backends write these
strings into ``events.event`` and the drakkar-ui SPA matches on them.
:class:`drakkar.recorder.schema.EventType` is the source of truth; this
script vendors it as JSON so the Go repo can pin the same list.

Usage::

    just gen-event-vocabulary            # rewrites tests/fixtures/
    just gen-event-vocabulary --out=DIR  # and a copy elsewhere

Copy the result into ``drakkar-go/internal/recorder/testdata/`` verbatim —
both repos assert against a byte-identical file.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from drakkar.recorder.schema import EventType

# Events one backend does not write yet. Kept as data so the gap is
# reviewable in one place rather than inferred from a failing parity test.
# ``offload``: the Go backend accepts ``offload.*`` config but does not run
# the pool, so it never records a row.
PYTHON_ONLY: frozenset[str] = frozenset({'offload'})
GO_ONLY: frozenset[str] = frozenset()

# Names that are broadcast on ``/ws`` but never written to ``events.event``.
# ``throughput`` is a periodic aggregate the UI renders live; buffering it
# would grow the events table without any query reading it back.
WS_ONLY: frozenset[str] = frozenset({'throughput'})

FIXTURE_NAME = 'event_vocabulary.json'
DEFAULT_OUT = Path(__file__).resolve().parent.parent / 'tests' / 'fixtures'

COMMENT = (
    'Recorder event-type vocabulary - a cross-backend contract. Generated by '
    'drakkar (Python) from drakkar.recorder.schema.EventType via '
    '`just gen-event-vocabulary`, and vendored byte-identically into '
    'drakkar-go at internal/recorder/testdata/event_vocabulary.json. '
    'Do not hand-edit either copy.'
)


def build_document() -> dict[str, object]:
    """Return the fixture body: the sorted vocabulary plus per-event owners."""
    events = sorted(member.value for member in EventType)
    emitted_by: dict[str, list[str]] = {}
    for name in events:
        backends = []
        if name not in GO_ONLY:
            backends.append('python')
        if name not in PYTHON_ONLY:
            backends.append('go')
        emitted_by[name] = backends
    return {
        '_comment': COMMENT,
        'events': events,
        'emitted_by': emitted_by,
        # True when the name appears in the events.event column; False for
        # the WS-only broadcasts. Both backends and the docs table are
        # checked against this.
        'stored_in_events': {name: name not in WS_ONLY for name in events},
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--out',
        type=Path,
        default=DEFAULT_OUT,
        help=f'directory to write {FIXTURE_NAME} into (default: tests/fixtures)',
    )
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    target = args.out / FIXTURE_NAME
    target.write_text(json.dumps(build_document(), indent=2, ensure_ascii=False) + '\n')
    print(f'wrote {target}')


if __name__ == '__main__':
    main()
